### ISSUE TITLE
Pas d'ipv4 dans motd

### ISSUE THREAD

**Issue by julpec** [labriqueinternet/build.labriqueinter.net#10]
Salut

Par flemmardise et manque de temps, je poste en français… dslé

L'ipv4 ne s'affiche pas toujours dans le motd (disons qu'elle ne s'affiche que très rarement, sur les 6 premiers reboots, elle ne s'est affichée que 2 fois).

Ça pose problème si on veut acceder à la machine facilement en tapant l'ipv4 dans un navigateur pour la post-install.

Après discussions sur l'IRC, il semble que ça puisse être un souci de motd généré avant que dhcp ait fait son travail

**Comment by jvaubourg** [comment]
Ce problème n'est pas lié à la Brique Internet, il s'agit d'un défaut de YunoHost lui-même depuis le passage à Jessie. Il faut reporter l'issue de leur côté.
