### ISSUE TITLE
Incomplete installation for Baikal app

### ISSUE THREAD

**Issue by julpec** [labriqueinternet/build.labriqueinter.net#11]
On a fresh install, the first app I have installed was Baikal but the installation failed.
It gave me this reason while I reached https://my-domain/baikal : 

> Incomplete installation
> 
> Baïkal dependencies have not been installed. Please, execute "composer install" in the folder where you installed Baïkal.

After that I tried to execute `composer install` in the baikal directory (i.e. `/var/www/baikal`) but it doesn't know the composer command : 

> root@olinux:/var/www/baikal# composer install
> -bash: composer : commande introuvable

Last days, I tried the stable image and I didn't have any problems with the Baikal app

**Comment by julpec** [comment]
I just found this thread and it's working by typing `usermod -s /bin/bash www-data` before installing baikal : 

https://forum.yunohost.org/t/installing-baikal-app-on-debian-x64-jessie-vps/542

regards

**Comment by bleuchtang** [comment]
ok so it's not a jessie image issue ?

**Comment by julpec** [comment]
yes it is
Sorry, I just see that I didn't mention that on my first post. This bug is related to the Jessie beta image.

**Comment by jvaubourg** [comment]
This bug seems to not be Brique-related. This should be a bug related to the usage of YunoHost with Jessie. Please, open an issue on the YunoHost side. Thx.
