### ISSUE TITLE
firmware-ralink and wifi tools

### ISSUE THREAD

**Issue by polytan02** [labriqueinternet/build.labriqueinter.net#12]
Hi guys,

[LaBrique] will be initially based on olimex equipment which includes MOD-WIFI-R5370-ANT. This wifi chipset is based on ralink and needs firmware-ralink in debian to work properly.

Also, no wifi tools (such as wpa_supplicant) are included at this stage, which could be a blocking point for those link me with wifi, serial connection but no ethernet available.

Please could you add these packages to the official [LaBrique] image ?

Thank you !

**Comment by jvaubourg** [comment]
Hi,

The Wifi Hotspot of the Cube installs firmware-ralink if you accept the non-free firmwares: https://github.com/labriqueinternet/hotspot_ynh/blob/master/scripts/install#L80

Currently, the Cube can only be connected to the Internet thanks to an ethernet connection. Wpa_supplicant is currently not useful.
