### ISSUE TITLE
No kernel updates

### ISSUE THREAD

**Issue by jvaubourg** [labriqueinternet/build.labriqueinter.net#16]
We have a custom kernel and this one is never updated.

We should find a solution for permitting to the users to update the kernel at the same time of the whole system, in order to have a least last security patches.

**Comment by bleuchtang** [comment]
Currently we have two choises:
- install our debian repository
- use testing kernel from testing

I will try to build an image with testing kernel and pinning kernel packages with security upgrade only.

**Comment by sbadia** [comment]
Hi! we 've take a look with @taziden, and all our needed features are merged in the testing (strech) kernel, and anyway, the 4.0 kernel ([linux-image-4.0.0-2-amd64](https://packages.debian.org/stretch/linux-image-4.0.0-2-amd64)) just entered in testing, so, :+1: for using Debian testing kernel!

**Comment by bleuchtang** [comment]
This is done now on latest images; we take the Debian kernel from testing.
