### ISSUE TITLE
[FR/EN] What soft are presents in a Olimex Internet Cube ?

### ISSUE THREAD

**Issue by Oliquae** [labriqueinternet/build.labriqueinter.net#19]
Hello,

The Raspberry Pi 2 has not support to convert it to an Internet Cube on Jessie. I succeeded to create a functionnal Yunohost on that version, and, I'd like to make everybody who wants to have profit on the raspberry flavoured hardware.

I want the support between Olimex Board and Raspberry Board are identicals. For that, I'd like to know what would be necessarry to install on the Debian, so there will be consistency.

I also saw that there was to create a image. Have I (or somebody else) to adapt for the rPi ?

Kisses

---

Bonjour,

Le Raspberry Pi 2 n'a pas de support pour le convertir en Brique Internet sous Jessie. Ayant réussi à créer une installation Yunohost fonctionnelle sous cette version, je voudrais faire en sorte à ce que tout le monde puisse en profiter sur ce matériel au goût de framboise. 

Je souhaite que le support entre les deux appareil soit identique. Pour ça, je voudrais savoir ce qu'il serait nécessaire d'installer dans le Debian pour qu'il puisse y avoir une cohésion entre les deux.

J'ai aussi vu qu'il faut des scripts pour créer une image, faut-il adapter pour le rPi ?

Bisous

**Comment by alexAubin** [comment]
Salut,

je réponds 3 ans et demi plus tard, mais au cas où : voici le script qu'on utilise pour transformer une image YunoHost en image de Brique : https://github.com/labriqueinternet/build.labriqueinter.net/blob/master/yunocube.sh

:sweat_smile:
