### ISSUE TITLE
Fetch app list from Yunohost community app list

### ISSUE THREAD

**Issue by keomabrun** [labriqueinternet/build.labriqueinter.net#43]
The list of apps (and their latest updates) should be fetched from the Yunohost community app list. Currently, this list is taken from a file hosted in labriqueinter.net:
https://github.com/labriqueinternet/build.labriqueinter.net/blob/master/build/script/hypercube/hypercube.sh#L332

**Comment by keomabrun** [comment]
Currently, only doctorcube is not on the Yunohost community app list.

**Comment by zamentur** [comment]
And doctorcube is not so useful...

**Comment by keomabrun** [comment]
I will propose a PR without doctorcube for now then.

**Comment by alexAubin** [comment]
https://github.com/labriqueinternet/build.labriqueinter.net/pull/42 ;P
