### ISSUE TITLE
Y U no modprobe?

### ISSUE THREAD

**Issue by pitchum** [labriqueinternet/build.labriqueinter.net#51]
The new build process based on lxc is almost functionnal.
But Wifi dongle is not automatically detected. 
Let's investigate why...

Workaround:
- Manually installing firmware-ath9k-htc from Debian testing
- modprobe ath9k
- modprobe ath9k_htc

**Comment by keomabrun** [comment]
https://github.com/labriqueinternet/hotspot_ynh/issues/35
