### ISSUE TITLE
Add possibility to execute custom script

### ISSUE THREAD

**Issue by SohKa** [labriqueinternet/build.labriqueinter.net#64]
Hello !

As explained in this ticket https://github.com/labriqueinternet/labriqueinter.net/issues/66, I think it would be nice to be able to execute a custom script at the end of the `hypercube.sh` execution.

I already did some work in the [install-sd.sh](https://github.com/labriqueinternet/labriqueinter.net/compare/master...SohKa:execute-custom-script?expand=1) and in the [hypercube.sh](https://github.com/labriqueinternet/build.labriqueinter.net/compare/master...SohKa:execute-custom-script?expand=1). Could you let me know if it's acceptable for a merge request ?

**Comment by pitchum** [comment]
Haven't tested yet but your changes look good to me.
Did you manage to build an install image including your changes?

**Comment by SohKa** [comment]
Hello,
Yes, using the `install-sd.sh`, I successfully built and installed the image on my cube : 
* with a custom script (it has been correctly executed and I could see its output in the "Hypercube debug" page)
* without a custom script (it's working as before)

Alright, I'll create a merge request, then. Thanks for your comment !

**Comment by pitchum** [comment]
it works for me \o/

**Comment by SohKa** [comment]
Great ! Thanks !
